Add tests

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -9,14 +9,39 @@ on:
     types: [released]
 permissions: read-all
 jobs:
-  test:
-    name: Test with python ${{ matrix.python }}
+  test_matrix:
+    name: Build test matrix
+    runs-on: ubuntu-latest
+    outputs:
+      paths: ${{ steps.paths.outputs.JSON_CONTENT }}
+    steps:
+      - name: Checkout the Git repository
+        uses: actions/checkout@v4
+      - name: Output matrix
+        id: paths
+        run: |
+          set -e
+          set -o pipefail
+          if [ ! -d tests ]; then
+            echo "Error: Failed to find tests directory"
+            ls -l
+            exit 1
+          fi
+          content=$(jq -ncR '[inputs]' <<< $(find tests -mindepth 2 -maxdepth 2 -type f -name VELBUILD | xargs dirname | xargs basename))
+          echo "$content"
+          echo 'JSON_CONTENT<<EOF' >> $GITHUB_OUTPUT
+          echo "$content" >> $GITHUB_OUTPUT
+          echo 'EOF' >> $GITHUB_OUTPUT
+
+  unit_test:
+    name: Unit test
     runs-on: ubuntu-22.04
     strategy:
       matrix:
         python:
           - "3.12"
           - "3.13"
+      fail-fast: false
     steps:
       - name: Checkout the Git repository
         uses: actions/checkout@v4
@@ -24,18 +49,63 @@ jobs:
         with:
           python-version: ${{ matrix.python }}
           cache: "pip"
-      - name: Cache test files
-        uses: actions/cache@v4
-        with:
-          path: |
-            .venv/bin/codexctl.bin
-            .venv/*_reMarkable2-*.signed
-          key: test-files-${{ hashFiles('Makefile') }}
       - name: Run tests
         run: make test
+
+  test_python:
+    name: Test python
+    runs-on: ubuntu-22.04
+    needs: test_matrix
+    strategy:
+      matrix:
+        path: ${{ fromJson(needs.test_matrix.outputs.paths) }}
+        driver:
+          - podman
+          - docker
+      fail-fast: false
+    steps:
+      - name: Checkout the Git repository
+        uses: actions/checkout@v4
+      - uses: actions/setup-python@v5
+        with:
+          python-version: 3.13
+          cache: "pip"
+      - name: Run tests
+        run: make test
+      - name: Run vbuild
+        run: |
+          set -e
+          if [ "$driver" == 'podman' ];then
+            echo "Starting podman service..."
+            mkdir -p /run/user/"$UID"/podman
+            podman system service --time 0 unix:///run/user/"$UID"/podman/podman.sock &
+            tries=0
+            while [ ! -S /run/podman/podman.sock ] && [ $tries -lt 60 ];do
+              tries=$(( tries + 1 ))
+              sleep 0.1
+            done
+          fi
+          echo "Running vbuild..."
+          source .venv/bin/activate
+          python -m vbuild -C "tests/${{ matrix.path }}" all
+          if [ "$driver" == 'podman' ];then
+            echo "Stopping podman service..."
+            kill $(jobs -p) || true
+          fi
+        env:
+          driver: ${{ matrix.driver }}
+      - name: Validate output
+        if: "!cancelled()"
+        shell: bash
+        run: |
+          set -e
+          tests/${{ matrix.path }}/validate.sh
+
   build-executable-ubuntu:
     name: Build executable for ubuntu
-    needs: [test]
+    needs:
+      - unit_test
+      - test_python
     runs-on: ubuntu-latest
     steps:
       - name: Checkout the Git repository
@@ -56,9 +126,12 @@ jobs:
           name: vbuild-ubuntu
           path: dist
           if-no-files-found: error
+
   build-executable-alpine:
     name: Build executable for alpine
-    needs: [test]
+    needs:
+      - unit_test
+      - test_python
     runs-on: ubuntu-latest
     steps:
       - name: Checkout the Git repository
@@ -91,12 +164,65 @@ jobs:
           name: vbuild-alpine
           path: dist
           if-no-files-found: error
+
+  test_executable:
+    name: Test executable
+    runs-on: ubuntu-latest
+    needs:
+      - test_matrix
+      - build-executable-ubuntu
+      - build-executable-alpine
+    strategy:
+      matrix:
+        path: ${{ fromJson(needs.test_matrix.outputs.paths) }}
+        driver:
+          - podman
+          - docker
+        artifact:
+          - "vbuild-ubuntu"
+          - "vbuild-alpine"
+      fail-fast: false
+    steps:
+      - name: Checkout the Git repository
+        uses: actions/checkout@v4
+      - name: Download executable
+        id: download
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{ matrix.artifact }}
+          path: dist
+      - name: Run vbuild
+        run: |
+          set -e
+          if [ "$driver" == 'podman' ];then
+            echo "Starting podman service..."
+            mkdir -p /run/user/"$UID"/podman
+            podman system service --time 0 unix:///run/user/"$UID"/podman/podman.sock &
+            tries=0
+            while [ ! -S /run/podman/podman.sock ] && [ $tries -lt 60 ];do
+              tries=$(( tries + 1 ))
+              sleep 0.1
+            done
+          fi
+          echo "Running vbuild..."
+          dist/vbuild -C "tests/${{ matrix.path }}" all
+          if [ "$driver" == 'podman' ];then
+            echo "Stopping podman service..."
+            kill $(jobs -p) || true
+          fi
+        env:
+          driver: ${{ matrix.driver }}
+      - name: Validate output
+        if: "!cancelled()"
+        shell: bash
+        run: |
+          set -e
+          tests/${{ matrix.path }}/validate.sh
+
   release:
     name: Add ${{ matrix.artifact }} to release
     if: github.repository == 'Eeems/vbuild' && github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
-    needs:
-      - build-executable-ubuntu
-      - build-executable-alpine
+    needs: test_executable
     runs-on: ubuntu-latest
     strategy:
       matrix:
